#! /bin/sh

bspc config borer_width 0

# Authentucation Agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & 


pgrep -x picom > /dev/null || picom &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII


bspc config window_gap 15

bspc rule -a Screenkey manage=off

# Time Specifc Wallpaper
python3 $HOME/.config/bspwm/wallpapers.py

# Cursor Fix
xsetroot -cursor_name left_ptr &

# Window Rules
bspc rule -a gnome-calculator state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a emacs state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a timeshift-gtk state=floating
bspc rule -a Timeshift-gtk state=floating
bspc rule -a Zathura state=tiled



# Autostart
fcitx -d &
picom

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch Polybar, using default config location ~/.config/polybar/config
polybar example &

echo "Polybar launched..."

ulauncher --hide-window
